--Zadanie 1
--Zadeklarować zmienną x z wartością 7. Dodać do niej 3, następnie przemnozyc przez 3 i wypisać poleniem print.
--Zadanie 2 
--Wypisać pętla while liczby o 1 do n gdzie n jest zmienną.
--Zadanie 3 
--Wypisać sumę kwadratow liczb od 1 do n tzn
--Np dla liczny n równej 3 było było to
--1*1+2*2+3*3 Czyli 14